parameters:
#    concerto_cms_markdown.example.class: ConcertoCms\MarkdownBundle\Example

services:
#    concerto_cms_markdown.example:
#        class: %concerto_cms_markdown.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
